FROM node:alpine

WORKDIR /app
ENV CHOKIDAR_USEPOLLING=true
ADD package.json package.json
ADD package-lock.json package-lock.json

RUN npm install

ADD src src
ADD public public
ADD README.md README.md

CMD ["npm", "start"]